
Podman requires you to create a virtual machine with user-specified characteristics *before* you can run an image. You can think of this as specifying the 'hardware' of the computer before you buy it (How much RAM? How big a hard drive? And so on.). In principle, this means that you can have more than one valid configuration at a time which would allow you to tune each virtual machine to your needs (one machine could have a lot of memory, another a lot of storage). 

Here's the quick-start version:

:::: {.panel-tabset}

### Apple MacOS

In iTerm2 you will type (hitting Enter after each line):

```bash
export CONTAINERS_MACHINE_PROVIDER="applehv"
podman machine init --memory 4092 --rootful
podman machine start
```

It is currently **essential** that you run these commands rather than just create a new machine from within the Podman Desktop. If you fail to specify that your Mac should use the Apple Hypervisor (`applehv`) you will end up with a machine that can't access the host file system. And if you fail to specify `rootful` you'll encounter a similar, though less challenging, issue when dealing with Quarto.

### Windows

In the Windows Terminal you *should* be able to simply type (hitting Enter/Return after each line):
```bash
podman machine init --memory 4092 --rootful
podman machine start
```

If you fail to specify that the machine is `rootful` then Quarto will not be able to run and you will receive permission errors when trying to render your assessment.

::: {.callout-warning}
### Unable to Run

In a small number of cases on Windows we've had error messages about permissions and been unable to `start` the machine that was created using `init`. In that case, it seems that you just need to create a new, named virtual machine (e.g. `podman machine init myvm`) and then change the default machine.

:::

::::

If you'd like to read more about fine-tuning your Podman machine we've [got a page for that](./podman_conf.qmd).

::: {.callout-tip collasped=true}
### Multiple Virtual Machines

If you'd like to run more than one machine, the interface for this seems a little clunky because all of the tools want to connect to the *default* machine. You can change this in the Podman Desktop, or on Mac/WSL you can create an environment variable like so:

```bash
export CONTAINER_CONNECTION=<name_of_vm>
```

Where 'name of vm' is the *other* virtual machine.

:::
